### ISSUE TITLE
Configurable HTTPoison timeout

### ISSUE THREAD

**Issue by cblage** [sbacarob/vantagex#18]
Hello!

Thank you for making this awesome lib.

Having a small issue and we can't seem to find a way to configure the timeout for the HTTPoison calls, and we've been seeing a lot of timeouts calling AlphaVantage lately. 

If you'd prefer, we (https://github.com/agentrisk) can open a PR to fix it. 

Unless there's a way to do it that is undocumented? 

Thanks!
Carlos

**Comment by sbacarob** [comment]
Hi Carlos!

Thank you for your kind comments and for reporting this issue. To be honest I hadn't thought about the possibility of passing opts allowed by HTTPoison, but I understand the improvement it represents.

Which is why I addressed it here: https://github.com/sbacarob/vantagex/pull/19.

I've added a bit of documentation for it on the README: https://github.com/sbacarob/vantagex#passing-httpoison-options

I'm closing this for now, because after merging that PR you now have the possibility to set timeout values in your config files. However, it would be very nice to have the possibility to permit it on a per-request basis, as HTTPoison allows.

If you'd like to tackle that, I strongly encourage you to open a new issue and address it. I think the changes it would bring could make for a 2.0 version, unless you could find a way to make it with backwards compatibility. I would love to make these changes myself, but right now I'm focused on other projects. If you're ok with a general setting for these timeouts, I could work on this in the next couple of weeks.

Please do let me know if you encounter any new issues with the addition of this new changes!

Thank you!
Santiago

**Comment by cblage** [comment]
Thank you!
